name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Deploy
      if: success() # Déploye uniquement si les tests réussissent
      run: |
        echo "Déploiement en cours..."
        # Ajoute ici les commandes pour déployer ton application
        # Par exemple, déployer sur Heroku, Azure, ou un autre service cloud
