name: Deploy to AWS Lambda

on:
  workflow_run:
    workflows: ["CI/CD"] # Nom du workflow de CI que vous surveillez
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # Assure que seul le dernier commit est récupéré

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package application
        run: |
          git archive -o source_code.zip HEAD # Crée une archive ZIP en respectant .gitignore
      
      - name: Unzip source code
        run: |
          mkdir -p /tmp/package
          unzip source_code.zip -d /tmp/package

      - name: Install dependencies
        run: |
          pip install --target /tmp/package -r requirements.txt

      - name: Create final deployment package
        run: |
          zip -r lambda_function.zip /tmp/package/.
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          zip_file: 'lambda_function.zip'
          function_name: 'predict'
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'eu-west-3'
